# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "8050:80"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./host:/etc/nginx/conf.d
      - ../:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектом
    volumes:
      - ../:/var/www
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: app_db
    ports:
      - 3305:3306
    volumes:
      - ./mysql:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8051:80
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysql
